name: Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download s
        run: |
          curl -s -o str
            "https://strelubin377-jpg&theme=tokyo
night&hide_border=true"

      - name: Commit and
        run: |
          git config use
          git config use.com
          git add streak.svg
          git diff --sta"Update streak"
          git push
